### ISSUE TITLE
x64retspoof

### ISSUE THREAD

**Issue by rafalohaki** [danielkrupinski/x86RetSpoof#2]
would be possible to fuse both codes into one?
1file for x86 and x64
https://www.unknowncheats.me/forum/anti-cheat-bypass/268039-x64-return-address-spoofing-source-explanation.html

**Comment by danielkrupinski** [comment]
- MSVC doesn't support inline assembly for x64, so it couldn't be a single file
- x64 has only one calling convention while x86 has a number of them

It wouldn't make much sense to have them together.
