### ISSUE TITLE
Osiris, CS:GO - memdumps of game at exit

### ISSUE THREAD

**Issue by ClaudiuHKS** [danielkrupinski/x86RetSpoof#3]
Since the x86RetSpoof update, when exiting CS:GO, on Windows, 2 memdumps are created.
C:\Users\Me\AppData\Local\CrashDumps

**Comment by ClaudiuHKS** [comment]
Anyone else experiencing this too?

**Comment by danielkrupinski** [comment]
It's not the issue with x86RetSpoof. The gadget becomes invalid because the .dll containing it is unloaded.
