### ISSUE TITLE
I don't get how to spoof __fastcall call.

### ISSUE THREAD

**Issue by R3BHXAB** [danielkrupinski/x86RetSpoof#4]
Hello,

So, I'm using this library for a few days, and i got an small problem.

I want to spoof __fastcall?
for example. I want to spoof call to SetClanTag (game / csgo)
I got an correct address to an function and i use it like that;
`x86RetSpoof::invokeFastcall<void>(0, 0, address, csgo::jmpEbxGadgetInClient, "clantag", "clantag");`
it leads to the following error:
![YKQLmX4F](https://user-images.githubusercontent.com/106755645/189928142-62f0063d-8632-4b5c-a705-98a19752a6c2.png)
when using __cdecl, this error doesn't happen, the function gets called, but strings doesn't get passed correctly which is causing some weird unicodes.

Can you please point what am i doing wrong and/or tell me how to fix it?

Thanks!

**Comment by danielkrupinski** [comment]
In __fastcall calling convention first two arguments are passed in **ecx** and **edx** registers. You should pass `"clantag"` (casted to `std::uintptr_t`) instead of 0s in the first two arguments to `x86RetSpoof::invokeFastcall()`.

**Comment by R3BHXAB** [comment]
Ah, yeah. I misunderstood the definition of __fastcall which says that. (literally first sentence on MSDN)
Thank you!
